"""add_user_id_to_members_and_memberships

Revision ID: e715fc883584
Revises: 
Create Date: 2026-06-08 06:18:33.617973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e715fc883584'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so existing rows aren't immediately rejected,
    # then enforce NOT NULL after populating/confirming rows.
    op.add_column('members', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.alter_column('members', 'user_id', nullable=False)

    op.add_column('memberships', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.alter_column('memberships', 'user_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_column('memberships', 'user_id')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_column('members', 'user_id')
    # ### end Alembic commands ###
